Board.create!([
  {name: "Favorites", user_id: 1},
  {name: "Vacations", user_id: 1},
  {name: "Favorites", user_id: 2},
  {name: "Vacations", user_id: 2},
  {name: "Favorites", user_id: 3},
  {name: "Vacations", user_id: 3},
  {name: "Favorites", user_id: 4},
  {name: "Vacations", user_id: 4},
  {name: "Towers", user_id: 3},
  {name: "Dream Trips", user_id: 3},
  {name: "Dark Tourism", user_id: 3},
  {name: "Europe 2020", user_id: 3},
  {name: "Euro-Food Trip", user_id: 3},
  {name: "USA Roadtrip 2018", user_id: 3},
  {name: "Tokyo 2019", user_id: 3},
  {name: "Hard to get to", user_id: 3},
  {name: "Japanese Food", user_id: 3},
  {name: "Secret Places", user_id: 3},
  {name: "Local Places", user_id: 3},
  {name: "Aussie Trip!", user_id: 3},
  {name: "Places I've been", user_id: 3},
  {name: "Discover Canada", user_id: 3}
])
BoardItem.create!([
  {post_id: 1, board_id: 9},
  {post_id: 3, board_id: 10},
  {post_id: 4, board_id: 11},
  {post_id: 5, board_id: 12},
  {post_id: 6, board_id: 13},
  {post_id: 7, board_id: 14},
  {post_id: 8, board_id: 15},
  {post_id: 9, board_id: 15},
  {post_id: 10, board_id: 12},
  {post_id: 11, board_id: 12},
  {post_id: 12, board_id: 11},
  {post_id: 12, board_id: 16},
  {post_id: 13, board_id: 17},
  {post_id: 13, board_id: 14},
  {post_id: 14, board_id: 10},
  {post_id: 15, board_id: 12},
  {post_id: 15, board_id: 10},
  {post_id: 15, board_id: 5},
  {post_id: 16, board_id: 15},
  {post_id: 17, board_id: 14},
  {post_id: 18, board_id: 6},
  {post_id: 18, board_id: 14},
  {post_id: 19, board_id: 12},
  {post_id: 20, board_id: 18},
  {post_id: 21, board_id: 19},
  {post_id: 22, board_id: 15},
  {post_id: 23, board_id: 15},
  {post_id: 24, board_id: 15},
  {post_id: 25, board_id: 19},
  {post_id: 26, board_id: 15},
  {post_id: 27, board_id: 20},
  {post_id: 28, board_id: 20},
  {post_id: 29, board_id: 20},
  {post_id: 30, board_id: 10},
  {post_id: 30, board_id: 12},
  {post_id: 31, board_id: 14},
  {post_id: 32, board_id: 16},
  {post_id: 33, board_id: 15},
  {post_id: 2, board_id: 5},
  {post_id: 8, board_id: 5},
  {post_id: 34, board_id: 6},
  {post_id: 35, board_id: 16},
  {post_id: 35, board_id: 5},
  {post_id: 36, board_id: 15},
  {post_id: 36, board_id: 17},
  {post_id: 37, board_id: 19},
  {post_id: 38, board_id: 21},
  {post_id: 39, board_id: 10},
  {post_id: 39, board_id: 16},
  {post_id: 40, board_id: 22},
  {post_id: 40, board_id: 6},
  {post_id: 40, board_id: 5},
  {post_id: 40, board_id: 21},
  {post_id: 41, board_id: 21},
  {post_id: 41, board_id: 19},
  {post_id: 41, board_id: 5},
  {post_id: 42, board_id: 15},
  {post_id: 42, board_id: 17},
  {post_id: 42, board_id: 5}
])
Category.create!([
  {name: "Africa"},
  {name: "Asia"},
  {name: "Australia"},
  {name: "Europe"},
  {name: "North America"},
  {name: "South America"},
  {name: "Activity"},
  {name: "Adventure"},
  {name: "Art"},
  {name: "Beach"},
  {name: "Breweries/Distillaries"},
  {name: "Cocktails"},
  {name: "Cultural"},
  {name: "Dark"},
  {name: "Desert"},
  {name: "Drinks"},
  {name: "Entertainment"},
  {name: "Family"},
  {name: "Foodie"},
  {name: "LGBTQ"},
  {name: "Hike"},
  {name: "Hip"},
  {name: "Historical"},
  {name: "Hotel"},
  {name: "Island"},
  {name: "Jungle"},
  {name: "Landmarks"},
  {name: "Museum"},
  {name: "Nature"},
  {name: "Natural Wonders"},
  {name: "Off-the-beaten-path"},
  {name: "Park"},
  {name: "Plains"},
  {name: "Resort"},
  {name: "Restaurant"},
  {name: "Road Trip"},
  {name: "Romantic"},
  {name: "Scenic"},
  {name: "Shopping"},
  {name: "Sights"},
  {name: "Solo"},
  {name: "Touristy"},
  {name: "Transportation"},
  {name: "Tropical"},
  {name: "Wildlife"}
])
Comment.create!([
  {text: "Say something!", user_id: 3, post_id: 36}
])
Location.create!([
  {city: "Sumida-ku", location: "Tokyo Skytree", lat: "357100.62699999986", long: "1398107.0039999997", google_id: "ChIJ35ov0dCOGGARKvdDH7NPHX0"},
  {city: "Shinjuku-ku", location: "Nabezo Shinjuku Sanchome Store", lat: "356911.6699999999", long: "1397036.4199999995", google_id: "ChIJX63OU9qMGGAReYZ5uABXAro"},
  {city: "Agra", location: "Taj Mahal", lat: "271750.151", long: "780421.5520000003", google_id: "ChIJbf8C1yFxdDkR3n12P4DkKt0"},
  {city: "Chornobyl", location: "Chornobyl", lat: "512763.027", long: "302218.99200000055", google_id: "ChIJz6uY6ACPKkcRLF3926vOvBQ"},
  {city: "Schwangau", location: "Neuschwanstein Castle", lat: "475575.74000000005", long: "107498.00400000026", google_id: "ChIJXaNOxMr3nEcRo7ud02uGpsg"},
  {city: "Düsseldorf", location: "Schweine Janes", lat: "512260.30399999995", long: "67728.14299999937", google_id: "ChIJecRByBnKuEcRCxauD9eqEow"},
  {city: "Anaheim", location: "Disneyland Resort", lat: "338104.85", long: "-1179189.8900000001", google_id: "ChIJg3XXhNrX3IARUc0M9bIC_X4"},
  {city: "Chiyoda", location: "Tokyo Station", lat: "356811.673", long: "1397670.5160000005", google_id: "ChIJC3Cf2PuLGGAROO00ukl8JwA"},
  {city: "Taitō-ku", location: "Sensō-ji", lat: "357147.651", long: "1397966.553", google_id: "ChIJ8T1GpMGOGGARDYGSgpooDWw"},
  {city: "Amsterdam", location: "De Poezenboot", lat: "523781.65699999995", long: "48931.32899999955", google_id: "ChIJrToBicgJxkcR5rI3Fa_U-yI"},
  {city: "Königswinter", location: "Schloss Drachenburg", lat: "506686.52999999997", long: "72063.73999999983", google_id: "ChIJeSC24qblvkcRHOpE2jLOkv4"},
  {city: "Darvaza", location: "Darvaza Gas Crater", lat: "402526.0309999999", long: "584397.004", google_id: "ChIJTTYILGbMYj8R0iPvFChvpK8"},
  {city: "Los Angeles", location: "n/naka", lat: "340251.2459999999", long: "-1184122.16", google_id: "ChIJb7GeyDS6woAROVvLEUiLZEk"},
  {city: "København K", location: "Noma", lat: "556828.273", long: "126104.80800000005", google_id: "ChIJpYCQZztTUkYRFOE368Xs6kI"},
  {city: "Polignano A Mare", location: "Grotta Palazzese", lat: "409958.71200000006", long: "172212.30099999957", google_id: "ChIJA5-2ZpPLRxMRGVjK7Uhed5A"},
  {city: "Shimonoseki-shi", location: "Nandan Sea Mall Ten Indian Cuisine", lat: "339489.914", long: "1309237.3569999996", google_id: "ChIJGeunH8q9QzUR_ajmUMyj1bk"},
  {city: "Portland", location: "Salishan Lodge & Golf Resort", lat: "455203.391", long: "-1226754.0350000001", google_id: "ChIJGRhzcAYKlVQRZwj2c16EVAM"},
  {city: "Cannon Beach", location: "Cannon Beach", lat: "458917.738", long: "-1239615.2740000002", google_id: "ChIJXc7PQCellFQRITpZ6kxP_hs"},
  {city: "Bilbao", location: "Guggenheim", lat: "432686.97499999986", long: "-29366.178999999873", google_id: "ChIJzWFZQd9PTg0ROu_13zH6b8I"},
  {city: "Victoria", location: "Little Jumbo Restaurant and Bar", lat: "484251.41500000004", long: "-1233692.9270000001", google_id: "ChIJIShj8Jp0j1QRcsWjkgzn4ac"},
  {city: "Whistler", location: "Whistler Brewing Company", lat: "500880.53", long: "-1230401.66", google_id: "ChIJYw2jzKwih1QR-Tw5H57pDIQ"},
  {city: "Chiyoda-ku", location: "Shangri-La Hotel, Tokyo", lat: "356825.66000000003", long: "1397694.4100000004", google_id: "ChIJL6nVJvyLGGAR8jHaHUYIL48"},
  {city: "Taitō-ku", location: "Andon Ryokan", lat: "357282.93", long: "1397955.1000000003", google_id: "ChIJ62o7D_OOGGARI0WkQJ0Jz8A"},
  {city: "Kyōto-shi", location: "Kinkaku-ji", lat: "350393.69999999995", long: "1357292.4309999996", google_id: "ChIJvUbrwCCoAWARX2QiHCsn5A4"},
  {city: "Vancouver", location: "Celebrities Nightclub", lat: "492792.977", long: "-1231301.093", google_id: "ChIJDfEopdRzhlQRiueE4hVtcag"},
  {city: "Kyōto-shi", location: "Gyukaku Kyoto Shijo Kawaramachi", lat: "350042.648", long: "1357702.4319999998", google_id: "ChIJ5yJoR5UIAWARGxOhubprsjU"},
  {city: "Petermann", location: "Uluru", lat: "-253444.277", long: "1310368.8220000004", google_id: "ChIJI1JibStsIysRIV_Fm03NqEM"},
  {city: "Sydney", location: "Sydney Harbour Bridge", lat: "-338523.063", long: "1512107.8710000005", google_id: "ChIJ49XqJV2uEmsRPsTAF7eOlGg"},
  {city: "Sydney", location: "Sydney Opera House", lat: "-338567.84400000004", long: "1512152.9669999995", google_id: "ChIJ3S-JXmauEmsRUcIaWtf4MzE"},
  {city: "Kraków", location: "Bungee Jumping Krakow", lat: "500607.89", long: "199681.9800000003", google_id: "ChIJMavnuTpbFkcRxFWsoB_pPF4"},
  {city: "Peach Springs", location: "Grand Canyon Skywalk", lat: "360120.20900000003", long: "-1138111.0690000004", google_id: "ChIJK0N3NakTzIAR5KnZMl6T5wA"},
  {city: "Chiang Mai", location: "Chiang Mai", lat: "187060.641", long: "989817.1630000002", google_id: "ChIJXW-7kH462jARZ0ObpXBi1Jg"},
  {city: "Chūō-ku", location: "Sushi Dai", lat: "356636.06299999997", long: "1397696.6870000002", google_id: "ChIJWZ1NO9mLGGART7JoN7C8oFI"},
  {city: "San Diego", location: "San Diego Zoo", lat: "327353.16", long: "-1171490.46", google_id: "ChIJyYB_SZVU2YARR-I1Jjf08F0"},
  {city: "ตำบล กื้ดช้าง", location: "Elephant Nature Park", lat: "192164.372", long: "988613.8559999994", google_id: "ChIJj21Ja6g62jARFSuw0w8gLNs"},
  {city: "Shibuya-ku", location: "sushi no midori", lat: "356583.4099999999", long: "1396989.8579999995", google_id: "ChIJo4dGzFeLGGARO7BvenQ8U3s"},
  {city: "Vancouver", location: "Tractor Foods", lat: "492804.70799999987", long: "-1231181.2859999998", google_id: "ChIJ721MUH5xhlQR0k6c0nxlXzk"},
  {city: "ตำบล ห้วยแก้ว", location: "Flight of the Gibbon - Chiang Mai", lat: "188653.001", long: "993485.0269999993", google_id: "ChIJ9ernAeWN2TARpRYHqbjCTGM"},
  {city: "Matamata", location: "Hobbiton Movie Set", lat: "-378723.441", long: "1756833.6130000001", google_id: "ChIJd0roN2KrbW0RpiH1qNZ8_yQ"},
  {city: "Gatineau", location: "Canadian Museum of History", lat: "454301.581", long: "-757092.0060000003", google_id: "ChIJL-0QIPEEzkwRxPx5idTJaKo"},
  {city: "Victoria", location: "Legislative Assembly of British Columbia", lat: "484196.17000000004", long: "-1233702.8499999996", google_id: "ChIJgcJti4R0j1QRHW6-NyyjuKg"},
  {city: "Ciudad Bolívar", location: "Angel Falls", lat: "81471.13700000002", long: "-635365.534", google_id: "ChIJjZOr2SaHzo0RQZbJBFkYC1c"},
  {city: "Pensacola", location: "Sushi Masa Hibachi And Grill", lat: "304703.29199999996", long: "-872079.8309999998", google_id: "ChIJy-YwEWzAkIgR0lAf7_oFXIM"}
])
Post.create!([
  {note: "Snackwave bicycle rights umami asymmetrical, flexitarian microdosing meh vice VHS chambray viral twee stumptown taiyaki cred. Tote bag church-key fam leggings, ennui food truck neutra bicycle rights readymade asymmetrical. Bicycle rights hoodie fam, occupy mumblecore blog stumptown iPhone portland. Hexagon lyft thundercats fanny pack, tumblr hammock everyday carry bespoke cardigan jean shorts tbh ramps tofu. Aesthetic bitters chambray iceland listicle. Lo-fi poutine poke four loko shaman direct trade.", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Tokyo_Skytree_2014_%E2%85%A2.jpg/1200px-Tokyo_Skytree_2014_%E2%85%A2.jpg", title: "Always wanted to go up the Skytree", user_id: 3, location_id: 1},
  {note: "Wolf meditation salvia organic pork belly YOLO fixie, master cleanse actually williamsburg. Mlkshk offal af organic, brooklyn tattooed raw denim swag knausgaard taxidermy palo santo lyft PBR&B paleo. Umami offal chia, godard salvia af ennui butcher selvage. Retro edison bulb austin authentic narwhal bespoke, tacos cred flannel snackwave.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA3nKjrK-A8R-bRU1Ccb8uYStZqOAIQjvLei6fYNHgqPa14b_DHBsPY2fTWIVZu8e5MlsNFztwB0K_UhUJ0FQyO4mr04IGcl5kmGCpIpXQr_0cmI71s7viUu51CF9PjZfVEhBon9ONaQLbrzZmV1ftuRGSGhQmU7IU__jk8e8IBb0_3Bh1EbKQlA&3u1960&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=80107", title: "My Favourite Nabe!", user_id: 3, location_id: 2},
  {note: "Fashion axe whatever DIY venmo green juice hoodie. Gentrify cloud bread selvage, four dollar toast intelligentsia seitan irony kinfolk aesthetic palo santo ugh synth. Etsy kinfolk iceland palo santo kickstarter, yr waistcoat gastropub succulents shabby chic typewriter pok pok tbh. Microdosing franzen hot chicken palo santo tumeric organic roof party quinoa gochujang crucifix distillery. La croix four dollar toast craft beer ugh asymmetrical, iceland farm-to-table lo-fi portland slow-carb disrupt fanny pack mumblecore umami fam. Raclette yr photo booth, deep v retro copper mug scenester affogato raw denim chicharrones. Hot chicken church-key stumptown, cornhole venmo gochujang +1 celiac mixtape messenger bag hashtag polaroid.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAnRdh_LkrEgcWSR3l9Xd9j5AhBf0vIgjPQUM5wIUQT0FEZmAkBJ0KxL4yZYDCv73TTLSL0UbEkQm4wWwDd1BoU2QxsL429sTt2Q7-wPpvsK0LCwuU3wdWBQPdhfcUD-TNEhA-cb9yvEUQlPXCYgISHqkkGhSoCMVddK8v_eRekBYdKlQBVFL30w&3u718&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=27848", title: "Let's go to the Taj Mahal", user_id: 3, location_id: 3},
  {note: "Vexillologist humblebrag pabst direct trade fanny pack put a bird on it asymmetrical normcore vaporware ramps seitan locavore. Tattooed pork belly scenester activated charcoal, synth glossier farm-to-table tumeric banh mi bicycle rights sustainable heirloom narwhal. Semiotics banjo retro quinoa sartorial shabby chic, fam cray listicle. Chillwave kombucha +1 portland single-origin coffee twee keytar franzen thundercats four dollar toast. Raw denim migas schlitz waistcoat.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAIshEeTYXM9q_vXttGEvKKH6n0Ah2wHh1NxLXKMKW6Rk_vR9kA8UNOcSrfUeGNC9HluxYBhYhIZX08IOn--phCkAFvXv-f25y1l8i-sUJQptOR-fFIaOpIz-0GuZEsmSWEhC2uLy8QsSgWOstIUjCzariGhQdxCoT8pHKOydycOERzk0KKf0wgg&3u4256&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=105009", title: "I really liked Chernobyl", user_id: 3, location_id: 4},
  {note: "Celiac shabby chic keffiyeh pug knausgaard man bun hell of everyday carry sartorial. Lomo meggings direct trade aesthetic cardigan. Literally microdosing ethical, farm-to-table small batch authentic try-hard subway tile etsy franzen. Tacos fam 90's ethical. Vape brunch humblebrag seitan, slow-carb pabst put a bird on it leggings irony selfies man braid shoreditch adaptogen. Ennui cronut bespoke narwhal tumblr schlitz. Quinoa cronut offal, blog pickled forage godard yuccie vegan tbh disrupt polaroid chia tumeric artisan.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAromXCZc2w70UycHouWTo0GmM9ic9aH122K4Z-dtpGwto79QhG7T9SulFMfKTC75nMDNFko7ZHOEg5IHyhl4utAHaeiZdNVwjtbO4qWq1NGv-k39AKcM9zOSBbAIstg5CEhBp8gz7oFtCDpbJxaK-mm0PGhSo9hnEHd8bJg1Oh152kedrHO8lPg&3u4288&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=85317", title: "Such a beautiful castle", user_id: 3, location_id: 5},
  {note: "Raw denim ramps cred, deep v cliche kale chips pop-up cloud bread leggings church-key man braid. Banh mi microdosing craft beer slow-carb. Green juice vice roof party yr pok pok edison bulb, photo booth palo santo cliche. Taxidermy chicharrones vice, hoodie viral photo booth godard salvia craft beer cray master cleanse crucifix prism. Snackwave godard drinking vinegar art party deep v. Hot chicken tbh franzen beard lumbersexual. Man braid plaid beard single-origin coffee jianbing pinterest poutine stumptown sartorial deep v banjo seitan.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAsUKTDQYq8Mmi8yO-9ZTsxHDJajFj4PBTy4tg9iqL85raTjXAPnBdUhBmQWQU5wki7wkXv6aDW4zUtrjv58LzcidCijwTa4HbKTcrYztea2retPJC5J6fW_3mDT7lPy5rEhAhZPzPw9mGdt8I_Gr5OcyXGhTihuqpU47OomXo2CGu_nPXA_ojLw&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=115203", title: "Amazing Schweinehaxe", user_id: 3, location_id: 6},
  {note: "Raw denim ramps cred, deep v cliche kale chips pop-up cloud bread leggings church-key man braid. Banh mi microdosing craft beer slow-carb. Green juice vice roof party yr pok pok edison bulb, photo booth palo santo cliche. Taxidermy chicharrones vice, hoodie viral photo booth godard salvia craft beer cray master cleanse crucifix prism. Snackwave godard drinking vinegar art party deep v. Hot chicken tbh franzen beard lumbersexual. Man braid plaid beard single-origin coffee jianbing pinterest poutine stumptown sartorial deep v banjo seitan.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAurWbXL_koJMQEKkjzBoiir2m3Y30GsOzJvNmcoe3U2UD4QqacO8Brqzvjmm1J1fW_KmwsxVdfxKl2Q07-F4BmnRkeCgaxJ-V0suiQdQZ8D5vwNTt6Yf7RYiaz54d_dkEEhBXWq85l2If8Zos2oz19UJVGhSFxsDDdzkfyXLycGeY4PBVdM49yQ&3u920&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=25554", title: "For when we have Kids.", user_id: 3, location_id: 7},
  {note: "Bespoke air plant listicle freegan dreamcatcher snackwave. Ugh mlkshk af prism, helvetica pabst williamsburg. Ramps knausgaard sartorial jean shorts. Cronut williamsburg paleo polaroid live-edge try-hard authentic. Flexitarian irony mustache, lumbersexual raw denim disrupt palo santo crucifix shoreditch hell of gochujang roof party authentic VHS wayfarers. Shabby chic hell of kogi vice DIY. Tote bag ramps forage jianbing swag cloud bread succulents.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAFyknYULTu6Gwxw2FjORJ2uN1gtMcGfQBrZFOHAH6z__RWRQOpIYRhj81ILSgp9OCr1tfUhIzOn0PVfjYYusQBW-fbsSuWhcXRKpvPy9JoA7NdX7_Dqo4TQS8Kz1yyf0REhCwFMs_d15m_sKNeTV80wP0GhTVvSf56OIQ8mXIw1AEzHaaXY6OZw&3u4032&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=2604", title: "We'll catch the Shinkansen", user_id: 3, location_id: 8},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAbcaNM-kE3IMTnjbY37aYzd5Dn9cJ17_Y2KeY1qdhNH81Tbir_BhgMzI7rRmjF8AN4txhuI727ypF8sRYiidc7JnGNJXDVyHnAb2_ss59_kv-u2YyaA1lyVeVyviSlHtNEhAzrrMdHfhPLc6jq-azL8W1GhRlqvuy-8vQc1XZ2sHMRI67SAURKQ&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=32306", title: "This temple looks so cool!", user_id: 3, location_id: 9},
  {note: "Green juice tilde organic chartreuse prism, migas scenester blue bottle ethical pug mlkshk PBR&B bespoke schlitz. Lyft succulents distillery pok pok tattooed mlkshk. Leggings succulents letterpress pitchfork. Marfa hoodie green juice DIY. Hammock aesthetic chia, keffiyeh schlitz beard trust fund next level hoodie. Squid fixie jianbing air plant, tofu af 8-bit prism listicle.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAZV5y2Fj2UnS_6EHRAGk4hmdWhw5DJbq2OO_qpqv_v2QFrx3RKGo2YG8s26OlGqZnIu0hDpKXwd-jP3S4EZZSeaynUv2z3IkZ36Bjkm_P_KlzhSoDAzTDak8iOD5L-Fi5EhC46f0nbgYF5TmyXIVd8U1DGhTpsvoAEF0mVaXcufSe3-xWOV5ivQ&3u5312&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=33077", title: "Let's go pet the kitties!", user_id: 3, location_id: 10},
  {note: "Kinfolk tbh you probably haven't heard of them blue bottle mlkshk. Intelligentsia lyft chartreuse live-edge, twee +1 man bun cliche activated charcoal fam polaroid tote bag. Shoreditch swag coloring book knausgaard heirloom chillwave keytar intelligentsia keffiyeh waistcoat taxidermy typewriter. Snackwave venmo banh mi polaroid, roof party tousled marfa. Plaid listicle normcore church-key hoodie.", photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Schloss_Drachenburg.jpg/1200px-Schloss_Drachenburg.jpg\" alt=\"Schloss Drachenburg.jpg", title: "I loved this castle", user_id: 3, location_id: 11},
  {note: "espoke air plant listicle freegan dreamcatcher snackwave. Ugh mlkshk af prism, helvetica pabst williamsburg. Ramps knausgaard sartorial jean shorts. Cronut williamsburg paleo polaroid live-edge try-hard authentic. Flexitarian irony mustache, lumbersexual raw denim disrupt palo santo crucifix shoreditch hell of gochujang roof party authentic VHS wayfarers. Shabby chic hell of kogi vice DIY. Tote bag ramps forage jianbing swag cloud bread succulents.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAvqTNfBUY2MiDK5tlx62HTdwEG3X-Nj0QJxo--NSuWHawrqUkinsqjtWVCbX7nj8XkvZQFkWNFhRb2dne-4fHPHnJ-pXJQKYWXXevVtxBvGcoZUJlI52PAofREskWR9h0EhCggVMXbdM_Kv2MXlN-_q9EGhQOnf4DnHcYkXtjKdMjYiCZ0nmcLA&3u4032&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=112575", title: "I want to see this Doorway to Hell.", user_id: 3, location_id: 12},
  {note: "Tofu sriracha tacos, sartorial green juice gentrify cloud bread craft beer. XOXO seitan disrupt, butcher letterpress VHS kickstarter listicle poutine tote bag small batch schlitz fam bushwick. +1 shaman forage, affogato bespoke pitchfork intelligentsia bushwick post-ironic DIY ennui mustache organic lo-fi schlitz. Disrupt mixtape helvetica, pok pok palo santo chia schlitz tousled pour-over. Tilde fixie wayfarers, health goth gastropub mustache flexitarian twee marfa blue bottle knausgaard beard shoreditch.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAS8pHsEwz2BdeuAsGUekmQwLdh8TgMMSXcni3OPRDY-bpSGpijk_joo5cDjUMrTnZF76YUrkTEYv8ggXuPE01Uyr7Qnd4oybyous4lB6FcVOZT6l6xbSEG172id8Xp4HDEhAl9Q6VNGzQ7ZMZVPFs7sdVGhRkobXgbcePqOsdwv2LudtSo1ixqA&3u1080&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=99215", title: "Need to try this Keiseki Place", user_id: 3, location_id: 13},
  {note: "Raw denim ramps cred, deep v cliche kale chips pop-up cloud bread leggings church-key man braid. Banh mi microdosing craft beer slow-carb. Green juice vice roof party yr pok pok edison bulb, photo booth palo santo cliche. Taxidermy chicharrones vice, hoodie viral photo booth godard salvia craft beer cray master cleanse crucifix prism. Snackwave godard drinking vinegar art party deep v. Hot chicken tbh franzen beard lumbersexual. Man braid plaid beard single-origin coffee jianbing pinterest poutine stumptown sartorial deep v banjo seitan.\n\n", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAxvFAzG6FKJ4TdTLMpPBlpdfd8EFWag_i48gfXbFi5qeXXqQWK7p87ck68ZPOuxeXYAOksDJsOPSliK20NR2uIbuERKetqyTuUMfDrWIEar7KGa4oadiNxoGSOk4adKDvEhAs85y-YMKSEZGVjdljyhj2GhTvE0sLI4qfxBpSzJ6c-P863JYZVA&3u4032&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=60158", title: "Best Restaurant in the world!", user_id: 3, location_id: 14},
  {note: "Bespoke air plant listicle freegan dreamcatcher snackwave. Ugh mlkshk af prism, helvetica pabst williamsburg. Ramps knausgaard sartorial jean shorts. Cronut williamsburg paleo polaroid live-edge try-hard authentic. Flexitarian irony mustache, lumbersexual raw denim disrupt palo santo crucifix shoreditch hell of gochujang roof party authentic VHS wayfarers. Shabby chic hell of kogi vice DIY. Tote bag ramps forage jianbing swag cloud bread succulents.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA6SVvUJpYnK2kzipC0T-TVmOq98QIatXWJAzAmrxMQBrOQdhoIKHbsGqMNPNLv9whZbVn7xwb7nR22u00Ose-nvifzPHhqzl-YIPMeyUTw1mXH_1vgQ8AGtoQPsPOZ9A-EhAFy8hQKDSzXNINN1PbbAG2GhSZysgFFdBmKPiMlVW6Z8HK9pjDbw&3u4032&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=79356", title: "So Romantic!!", user_id: 3, location_id: 15},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA5pM5hNXN2rhx6Q6RmD62lofjCZYi8YlUswhz5c0nN9DWhpQDYswAxMTUejien-zSudMh0HOSGhuMYParh2u388O7w80FG4xPDB9ca1E7NxjwEZv81GbFOdazE_oH630LEhDkt9-o9-WUxe9gmXrnYA7ZGhSd8YVpfegIJ0ZUqEgWlwcEpoOPMw&3u5312&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=87553", title: "Delicious Curry in the middle of Japan!", user_id: 3, location_id: 16},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAVmNvIS6qfyxaKRLTfNrXCnqdJLsH3oczUeHpi2M4mvL0fzY3yEbYkYKCrOBT_6pH7sPI3FS_pf9vIXhq1quunahwTfnhuBALDNj6zVqrsCqGcjN79U_4uLo3Fc4puUWNEhBJOuVF8iV92vBduAyoHz08GhTeVEKBiZ9rxaxIcCjx3HvilY-rNw&3u3024&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=73953", title: "Favourite Resort", user_id: 3, location_id: 17},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAALk8PXvJC0qhKFp7SodrBgC794h06KLJ-Sk4YYq2bWwRn-9Cl8LDZr4M5CfM4yPk5LDY_zU6Rt5N3tKLIu7nR6b0ri_dBiPSn0xJrtAH6OzW6KasoWG7nPaSNsSAXZONUEhCU_-BQUhvmH2y9iXB3HFfnGhQOQ000koUKkvY5-tBrUbmsDhXNPQ&3u4608&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=90903", title: "Beautiful Beach", user_id: 3, location_id: 18},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAzN-4V1KrkT347Vx9b-jUwShmjGT86ExvR-PGQd3CjlVgNAeaXHTVh3E8F59Z07jeUMtg28eXqE1liiuOQeZo5qRLYByOenJobI73SmBZHNrGca4r1d8lCYt8stt2F0bYEhC3fJ73dRGCsni1vjfgKZyBGhQG5WXK3orKhv3u9Gp369kFhGlIAA&3u1920&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=32541", title: "Nice art museum", user_id: 3, location_id: 19},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRZAAAAt4lM843EkluDb69JIOmikrGzSZmlAGLzUjjHKPnPy24pFQhM3muT8kXn210IfNWkx5y44m3kEB2VNt864sC-fRfDDK3_-P0BkR7d_4RmHy-wqxGHiLX9CoaO8FD6jEEtEhDFPd16ukO0wedYj6dy-HqWGhQJXLNzlYqPKRBr2uNdibmp96UBEw&3u3264&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=11645", title: "Great cocktails", user_id: 3, location_id: 20},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAdXvD3CO5avTYJbEgJBlPr0vtsq-Yqz79GzV7D6GTsIYP3vTRwOv4k67vkjh0nK1R5HITn4eV1_RPnUudBu4yqPblc-tAPqNoZFBg5jxACnb4N6dpmWb5acMlp7335Qp7EhDBzl_-HpDgpbCGxtl7m-l_GhQDGjk2EUZw6chPBMXJ-n_77oTVTQ&3u5184&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=115836", title: "Good beer!", user_id: 3, location_id: 21},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA65dzwqB9iTfSWKLt0D4uR4r2EvrHvNfrlAKbQcVuSuJw5ePet7Td4Nr2DxOV76ZEDkE8gd4XlegW95H27leAFciOlH-IAGbqh7rdLNRvgBWbgkAJBzSIhC-vjWzDmEHeEhDg6dHJ37gbCgWTl3DyQ-YtGhTs5orbmmlib5e7bax-xsQn2DkN5w&3u6000&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=2475", title: "Beautiful Hotel", user_id: 3, location_id: 22},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAaYzJGg0Xk7WUqRbAiid8rqcMFOADBPvJByUvDhc-sLH4YCT4eHFC3UlobrBLuabhZWZWx5ov5LdOQ0Ea0fQFKtXrTNXq1JdMgRIqq1ZLwGQ8GtFdJ7JyxH8PAK9K4_SIEhABOcP7nnaEkHlXA8jScgzrGhQphfdOD-fAEI0fvUNTQcxTF3NCkw&3u4256&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=58120", title: "My Favourite Ryokan", user_id: 3, location_id: 23},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA4ty_UZcG3cKBThSUDpjTNhsIWK51qZ15DCEfe5Xil0nw-0wozVeVg86OtHqsCFRdmPb3d-I3qbcR69WYqk0tHu4ej8kPliK5oirlj6QPRzRTGscESFji223IV2nhsnN6EhDj7E2Kk8seKIG27dSTvRgDGhSNTnXRuiZlfOpw9OJ3A-GIdvogww&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=64318", title: "Such a cool temple", user_id: 3, location_id: 24},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAZckdQX5fC8YEJXIJYm47vtb4eZA0fsOQT9kODQslUpl8SYo9_LYr3zRaqU4P5mbbOEO6SGqMIsMxaLhSTWlq-sV6-f5QJvAuc2U7yXm7_sCTF8diTjTyysEPC6fgxFZSEhD6vAfwQ9VkE8wqG2PRjJs_GhTDZHFxCd1bDKQyW6FA4nrL_N4A_w&3u3771&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=120533", title: "Great gay bar!", user_id: 3, location_id: 25},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA7x5W63F10HY6uB6mXJ6nwHxd3RFwQjmJceKAd7TXKtnV-wX-ZVH8mn69tfl7lsZZYSxnlyXIgmF2ywDEVhP9isJGiDgW6zFXelGsDXAr2EnSLAuxwXs6jKoP94F7JmG1EhCX893hlwky731Egat9pkXtGhTXJvtlcJgv0fsJrnVy6V3gVafsEw&3u3264&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=10775", title: "Delicious fire-meat", user_id: 3, location_id: 26},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAnxqvnnOBvJ9-YAgEy1nEYhHLOa44WZvrh6V1rOYPX5aUD6Fp9Db1MJ-fseYG2c839g_fIvAew0J7T5VVyq5aE9reZHg3bMEHFCgHeyM3VHluWKgNe-6sLJ0xKWcQdcFBEhDldxCzw7JjtOsJ0HvYwfS4GhT7jmJhHcImgGv36SaGzDHKFoT0YQ&3u3264&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=12631", title: "It's a rock.", user_id: 3, location_id: 27},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAk1CeVXLMf8ryE7oRO879hEQ2B4sGUGv1Jd9ymQ0NycyhehoEcc8c0sDwUEA5FnPVzLMiACBHO2XUN_tLzQLmaDEAyEshK7BqdDjvL_zA7ZVvwogsmPMJ0suNO34-NXsBEhDspyxy2ZnR4BTNNypg86JlGhRV8azQu0ZUQ8ckqEGTOLPiE5L5Rg&3u4592&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=107808", title: "Fun Bridge!", user_id: 3, location_id: 28},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAHUbuvZlyrryq29g4O-NtV7O2ZXmu7PxHEaTuKefrf2NWSx_kDs7O7QXrsv7kJ2t-dYZGH4V_4IoGrftqOcMfbSclKngnTMJYa68JJ-6I_UxtFsnqqS3A44TKzlqsG22rEhBdHCSJ3dJrwDNM9XllAzykGhQt6XtygsLY5jQXzqYhDz83lKFirg&3u4000&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=102702", title: "Great acoustics!", user_id: 3, location_id: 29},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAE-i10_EyZGO8fE3w4_QDEGtkuwxDOsTTdh14z3P4_r514Hh38NzYBQAMCW6oNkJq50IfJ7GSTkLPBY9Vl7jThfS_Rb8sDxeF6OCQ2_nmZs8B12POANLws0ka-Is_4azaEhA8_gocyAKcDUp2LpLd73oCGhTh-c6gZNfccLg-CSDxOctnRXcf3g&3u4288&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=68049", title: "Wheee", user_id: 3, location_id: 30},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAaa0jflAcfD7w_oXS7h8M62-vuJHCXmMiavNvf6x36e4RpyT9YJzf-oPmTOKqJHvVQPeSIDvM499NOz1szytxjQLzmLSbM1QeaTcEDhNyEUEuX_2fTKpXL5camUmsxv-UEhAedrYwtB6Lr_A6rhsrESH7GhR62_XF7zIJLQeRZPbESFVv6Nwp9A&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=78460", title: "Great spot for a hike", user_id: 3, location_id: 31},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAmsax7OaWo9XvANXM3v7IsjL2rSBCIyjCjoEVayLUOOlzkLJX8KiJHIaupt0w-ZLNs_fylh0xB4JthFc5mQgTfXViJuB6zPxrBJ1BEylOmZYcaSUcdR3Q7-jj0968Lh2EEhAAoWAAjUHZl56jkPHGyTQ1GhREqWBCZz8bECfLUuLV0aSWgCf8PA&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=89863", title: "Jungle time", user_id: 3, location_id: 32},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA8HPMGGdiJtKjF0FbFtbkjxjC8XLmaRmUnqBbxrVHlBunbwqs8BbxIMUhjRtNiKYzQyR2ZRf1dqzxRyhEUWDWYSOQaFb9dkXh_FFnLZyEkUDEFVQjWiYIXc3acNx8UFdiEhD4ZwhbW3JmNJh0uZ1FATJEGhRqiyoRwhVs1bVljXl09o1qi1gw0g&3u4618&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=4777", title: "This place looks tasty!", user_id: 3, location_id: 33},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAq-6ouPEM8NcHFlVfaBbeO5xGf2YPJiduuHFrygpPjp1vEpKnXWkjAzWPBug0oQlU3bCMOUhLBRpy1t_OIBlJ51x2PeAMxLMI2A9HXEX-SuHxknMmrzSO5gqWBi7j7-HSEhAmn_IAlxGWMmh6csZuYzCuGhTMglR26sRkJgR0hqW5y2VlUTgE9g&3u6000&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=127709", title: "It's a zoo", user_id: 3, location_id: 34},
  {note: "VHS godard wolf occupy, chartreuse venmo succulents keytar mlkshk crucifix. Hell of flannel pabst godard try-hard health goth messenger bag blue bottle pok pok microdosing YOLO roof party butcher narwhal migas. Hoodie yr shaman, gluten-free DIY umami waistcoat shoreditch YOLO street art swag edison bulb snackwave bespoke fingerstache. Man braid hot chicken cold-pressed seitan chambray distillery, wolf mixtape single-origin coffee chicharrones banjo yr. Fanny pack woke banh mi retro direct trade, williamsburg ramps flexitarian fam. Gluten-free sustainable vexillologist wayfarers photo booth.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA9-C4cVUaIvYa92N5MKgcq-wRO6SRQY4jIFAQ1IIJaMyU7fyyKnRCo7gOu2vJpfCOj0zTKpYUnZo8mRi_z-H1AP_WMhf5Jg3_Lvy4pfovavZedpei-F_9_Yu_Ivrgg6-OEhDLvuDY2OP9Iq67b3feLvDqGhRjIOc0HjLTJsqV3WcKMi7suOld8A&3u4048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=34041", title: "ELEPHANTS", user_id: 3, location_id: 35},
  {note: "Gotta go here in Shibuya.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAeSeSYXNegSQ3DUOOnTWYRcYDjsnL7h3-tY3Yiv3FwppTMsswQOgF2bHZlhaC0kWh37a2gEZXLvYKUqwGHq_Mr32PXMmCemvY-UUCks_iywXzhUTRR6eHftFyia9M84mQEhCbviLOh5LuH3UFbCz9s3mQGhSfoaapGv9M5E-odQ9h0Tqge4J8KQ&3u4032&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=128331", title: "Looks like good sushi!", user_id: 3, location_id: 36},
  {note: nil, photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAZIF7o2LmIsOc8MUGJ_hSKihwnO0LODMcmyV6dOHYOUbTYUW6Y2l7bIBz4JVAdhHBa0k1GgUnEAr-vTWnOcHj_YWdDcRA3pc6zgOcqgp9W60jV20T2B4bo4F_vn5-J5uTEhBKh8q_n_riflK5Chul41DMGhTnlQPT5kvjDy53HW3IOGrPZPdUsA&3u5333&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=20558", title: "ff", user_id: 3, location_id: 37},
  {note: "Vice tousled man braid street art, palo santo gluten-free man bun sriracha kale chips chia enamel pin yuccie. Farm-to-table crucifix hot chicken tumeric stumptown skateboard franzen, palo santo sustainable synth austin chartreuse shoreditch deep v leggings. Pinterest cred photo booth narwhal. Flexitarian waistcoat next level microdosing small batch. Vexillologist hot chicken chartreuse tousled portland succulents hexagon lomo.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA-9ZZlWIEGtc1MRjpMDanYv4C2R7OJfyr6x16DP9cRc_EQDCMtJgxUqJlokJYvTywnR8rX4xSIa-GfHSgP-RNl-3Vkg9UgNS9bMN0YFgl8maGNYtHY_DXNy3d4D-kUjP6EhA2De_f2XgA-bWLCjyoRSouGhQvGA86_66F0d9D-Th9VkK27b9qAQ&3u4896&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=80406", title: "Such a fun day.", user_id: 3, location_id: 38},
  {note: "Vice tousled man braid street art, palo santo gluten-free man bun sriracha kale chips chia enamel pin yuccie. Farm-to-table crucifix hot chicken tumeric stumptown skateboard franzen, palo santo sustainable synth austin chartreuse shoreditch deep v leggings. Pinterest cred photo booth narwhal. Flexitarian waistcoat next level microdosing small batch. Vexillologist hot chicken chartreuse tousled portland succulents hexagon lomo.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAABPugoWK9qlCKnY1mnMvDLl4OM3Jumxs0XcG1lzENa4jZFZwkeXMCX3fPOH_MlxmINFXv2zVSl04l5YJRqx_IakPSv5cX7FIUft6_lCz0lrmmJcU_mWZnHfHlarTuX8JdEhBVx1izWd8IRiC-ksfEIsknGhTkJNP--7NgnVb_zdAOTUhV42fXgw&3u3456&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=333", title: "Such a cute set", user_id: 3, location_id: 39},
  {note: "Vice tousled man braid street art, palo santo gluten-free man bun sriracha kale chips chia enamel pin yuccie. Farm-to-table crucifix hot chicken tumeric stumptown skateboard franzen, palo santo sustainable synth austin chartreuse shoreditch deep v leggings. Pinterest cred photo booth narwhal. Flexitarian waistcoat next level microdosing small batch. Vexillologist hot chicken chartreuse tousled portland succulents hexagon lomo.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA9XYPd0V8Z3PvrZAdxcgj5ockJKj46UBcqy-7KJA8AjQgdeen4Q-RINwKq9dz714KSAP078BbxSaUcnOJT46QryUguaw-ERdysCAWPknr0QlQodnNBT9Qaj0ji9zDfYVLEhDsj0JoMuw39Dnqv6KD2HDyGhQCKd8Uxfv8KHPN1p5H6JlmqJLcOg&3u2048&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=34849", title: "Great Canadian Museum", user_id: 3, location_id: 40},
  {note: "Vice tousled man braid street art, palo santo gluten-free man bun sriracha kale chips chia enamel pin yuccie. Farm-to-table crucifix hot chicken tumeric stumptown skateboard franzen, palo santo sustainable synth austin chartreuse shoreditch deep v leggings. Pinterest cred photo booth narwhal. Flexitarian waistcoat next level microdosing small batch. Vexillologist hot chicken chartreuse tousled portland succulents hexagon lomo.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAA_c0sHli84jmPN54xK597EHgV4zRdk7yn4TEOIK2x895__gWHt6AsJFvV98jm18XtSjYY2TlBMnBT3YLdRzoQkylQ95392r9uV3NMvReMhB64s9HDjPa-IdMSr1Q2oGcnEhBduzO2YBO6R3uy1tb0DQjJGhSOnVL-2UAUCEgBXwsPrAnfQLjyyw&3u4163&5m1&2e1&callback=none&key=AIzaSyCqC3YhZScKNM541GdXrJ4FXFU0tluWtgQ&token=52735", title: "Awesome Architecture", user_id: 3, location_id: 41},
  {note: "Vice tousled man braid street art, palo santo gluten-free man bun sriracha kale chips chia enamel pin yuccie. Farm-to-table crucifix hot chicken tumeric stumptown skateboard franzen, palo santo sustainable synth austin chartreuse shoreditch deep v leggings. Pinterest cred photo booth narwhal. Flexitarian waistcoat next level microdosing small batch. Vexillologist hot chicken chartreuse tousled portland succulents hexagon lomo.", photo_url: "https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAauJlQ3UBmv2hpx8JGSZgfz_O3RdQ7t2Hy3n02kHSpwdQ9Br-3a3OHRBgcXj0-m1P-C8OQ2s1HlXKxrL6zSjBSZ5kWU1ZLcJo15eQM5mW52QHnlN4a1DKBhR4MSj22WGaEhCAS1A6_JmR7gGwZU2HsMytGhQl-i8_F8K4ei0xdFJJj33jK2mofA&3u5312&5m1&2e1&callback=none&key=AIzaSyC1I4rc72v5cAK3VPLXYKLnUmISNzM5AYs&token=118295", title: "Looks like good sushi", user_id: 3, location_id: 43}
])
PostCategory.create!([
  {post_id: 1, category_id: 2},
  {post_id: 2, category_id: 35},
  {post_id: 3, category_id: 27},
  {post_id: 4, category_id: 31},
  {post_id: 5, category_id: 38},
  {post_id: 6, category_id: 19},
  {post_id: 7, category_id: 18},
  {post_id: 8, category_id: 43},
  {post_id: 9, category_id: 13},
  {post_id: 10, category_id: 17},
  {post_id: 11, category_id: 23},
  {post_id: 12, category_id: 8},
  {post_id: 13, category_id: 5},
  {post_id: 14, category_id: 19},
  {post_id: 15, category_id: 35},
  {post_id: 16, category_id: 35},
  {post_id: 17, category_id: 34},
  {post_id: 18, category_id: 10},
  {post_id: 19, category_id: 9},
  {post_id: 20, category_id: 12},
  {post_id: 21, category_id: 11},
  {post_id: 22, category_id: 24},
  {post_id: 23, category_id: 22},
  {post_id: 24, category_id: 23},
  {post_id: 25, category_id: 20},
  {post_id: 26, category_id: 16},
  {post_id: 27, category_id: 15},
  {post_id: 28, category_id: 3},
  {post_id: 29, category_id: 3},
  {post_id: 30, category_id: 7},
  {post_id: 31, category_id: 21},
  {post_id: 32, category_id: 26},
  {post_id: 33, category_id: 2},
  {post_id: 33, category_id: 19},
  {post_id: 33, category_id: 35},
  {post_id: 34, category_id: 45},
  {post_id: 35, category_id: 45},
  {post_id: 35, category_id: 44},
  {post_id: 36, category_id: 2},
  {post_id: 36, category_id: 19},
  {post_id: 36, category_id: 35},
  {post_id: 37, category_id: 35},
  {post_id: 38, category_id: 26},
  {post_id: 38, category_id: 29},
  {post_id: 38, category_id: 31},
  {post_id: 39, category_id: 21},
  {post_id: 39, category_id: 22},
  {post_id: 39, category_id: 30},
  {post_id: 39, category_id: 31},
  {post_id: 39, category_id: 32},
  {post_id: 39, category_id: 33},
  {post_id: 40, category_id: 5},
  {post_id: 40, category_id: 7},
  {post_id: 40, category_id: 13},
  {post_id: 40, category_id: 23},
  {post_id: 40, category_id: 27},
  {post_id: 40, category_id: 28},
  {post_id: 40, category_id: 36},
  {post_id: 40, category_id: 42},
  {post_id: 41, category_id: 5},
  {post_id: 41, category_id: 13},
  {post_id: 41, category_id: 27},
  {post_id: 41, category_id: 36},
  {post_id: 41, category_id: 40},
  {post_id: 41, category_id: 42},
  {post_id: 42, category_id: 2},
  {post_id: 42, category_id: 35}
])
User.create!([
  {first_name: "Geoff", last_name: "geoffff", email: "geoff@test.test", password_digest: "$2a$10$Nmq4W9Fpq4/4fsrVt0Blr.OVhGJ2cQ7h1h5qJjliTxMudZcQ6FBaa"},
  {first_name: "Kyle", last_name: "kyleeee", email: "kyle@test.test", password_digest: "$2a$10$ATsa3MprRphzKn3zqa7DL.s6t2dliVlvwIoGEIXVtFlwyekmNPl52"},
  {first_name: "Alex", last_name: "alexxxx", email: "alex@test.test", password_digest: "$2a$10$GUaFGDb2Hcg2q8NBtzZ9KewY60R3KJv0dz4Ro2zVy4xj8WvXNeIQC"},
  {first_name: "Guy", last_name: "guyyyyyyy", email: "guy@test.test", password_digest: "$2a$10$ELaFCAJU38Js/XQm26P12ubtQjXwbF0hQhVzhVw7lMyLvD3wQumr6"}
])
